"""add booking table

Revision ID: 02f1f1da070e
Revises: c567f2073005
Create Date: 2024-04-07 22:56:47.891734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f1f1da070e'
down_revision = 'c567f2073005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('pick_up_location_id', sa.Integer(), nullable=False),
    sa.Column('drop_off_location_id', sa.Integer(), nullable=False),
    sa.Column('pick_up_time', sa.DateTime(), nullable=False),
    sa.Column('return_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['drop_off_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pick_up_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
