"""Car 新增Status來記錄車輛狀態

Revision ID: 2f1b2fb2ddf5
Revises: 8310e9a83169
Create Date: 2024-05-08 14:28:21.362339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1b2fb2ddf5'
down_revision = '8310e9a83169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('Status')

    # ### end Alembic commands ###
