"""CREATE cars 欄位

Revision ID: ad7521c20d43
Revises: 6b0bcc63512d
Create Date: 2024-04-21 11:02:26.408055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7521c20d43'
down_revision = '6b0bcc63512d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('door', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('width', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('height', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('door')
        batch_op.drop_column('body')

    # ### end Alembic commands ###
