"""create booking_count col in car table

Revision ID: cb30179b0c8e
Revises: 5764097b9d8c
Create Date: 2024-04-27 10:10:35.531930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb30179b0c8e'
down_revision = '5764097b9d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('booking_count')

    # ### end Alembic commands ###
