"""booking 新增Status來記錄訂購狀態

Revision ID: e78fab029d81
Revises: 2f1b2fb2ddf5
Create Date: 2024-05-08 14:42:11.106215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78fab029d81'
down_revision = '2f1b2fb2ddf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('Status')

    # ### end Alembic commands ###
